#!/usr/bin/env python3
"""
Simple wrapper for adding LeetCode problems

Usage: ./add_one <problem-slug> [-r]
Example: ./add_one count-negative-numbers-in-a-sorted-matrix
         ./add_one count-negative-numbers-in-a-sorted-matrix -r
"""

import sys
import os

# Add utils to path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'utils'))

from add_leetcode import main

if __name__ == "__main__":
    sys.exit(main())

